CREATE DATABASE IF NOT EXISTS emsi_shop
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE emsi_shop;

CREATE TABLE IF NOT EXISTS ARTICLE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PRIX DOUBLE NOT NULL,
  QUANTITE INT NOT NULL,
  PRIMARY KEY (ID)
);
